export const CREATE_NBA_MODEL = 'nba/models/CREATE_NBA_MODEL'
export const FETCH_NBA_MODELS = 'nba/models/FETCH_NBA_MODELS'
export const DELETE_NBA_MODEL = 'nba/models/DELETE_NBA_MODEL'
export const UPDATE_NBA_MODEL = 'nba/models/UPDATE_NBA_MODEL'
export const FETCH_NBA_MODEL = 'nba/model/FETCH_NBA_MODEL'
