export const LOGIN = 'auth/LOGIN'
export const LOGIN_FAILED = 'auth/LOGIN_FAILED'
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS'
export const CLEAR_LOGIN_ERROR = 'auth/CLEAR_LOGIN_ERROR'
export const UNAUTHORIZE = 'auth/UNAUTHORIZE'
export const AUTHORIZE = 'auth/AUTHORIZE'
