export const CREATE_USER = 'auth/CREATE_USER'
export const CREATE_USER_FAIL = 'auth/CREATE_USER_FAIL'
export const CREATE_USER_SUCCESS = 'auth/CREATE_USER_SUCCESS'
export const UPDATE_USER_PASSWORD = 'auth/UPDATE_USER_PASSWORD'
export const UPDATE_USER_PASSWORD_SUCCESS = 'auth/UPDATE_USER_PASSWORD_SUCCESS'
export const UPDATE_USER_PASSWORD_FAIL = 'auth/UPDATE_USER_PASSWORD_FAIL'
export const FETCH_USER = 'auth/FETCH_USER'
export const FETCH_USER_SUCCESS = 'auth/FETCH_USER_SUCCESS'

// Billing and Subscription
export const FETCH_BILLING = 'auth/FETCH_BILLING'
export const CREATE_BILLING = 'auth/CREATE_BILLING'
export const UPDATE_BILLING = 'auth/UPDATE_BILLING'

export const FETCH_SUBSCRIPTION = 'auth/FETCH_SUBSCRIPTION'
export const CREATE_SUBSCRIPTION = 'auth/CREATE_SUBSCRIPTION'
export const CREATE_INITIAL_SUBSCRIPTION = 'auth/CREATE_INITIAL_SUBSCRIPTION'
export const UPDATE_SUBSCRIPTION = 'auth/UPDATE_SUBSCRIPTION'
export const DELETE_SUBSCRIPTION = 'auth/DELETE_SUBSCRIPTION'
