export const FETCH_NBA_GAMES = 'nba/games/FETCH_MATCHES'
export const PAGINATE_NBA_GAMES = 'nba/games/PAGINATE_NBA_GAMES'
export const FETCH_NBA_GAMES_SUCCESS = 'nba/games/FETCH_NBA_GAMES_SUCCESS'
export const PAGINATE_NBA_GAMES_SUCCESS = 'nba/games/PAGINATE_NBA_GAMES_SUCCESS'
