export const FETCH_NBA_BETS = 'nba/games/FETCH_NBA_BETS'
export const FETCH_NBA_MATCH_BET = 'nba/games/FETCH_NBA_MATCH_BET'
export const CREATE_NBA_BET = 'nba/games/CREATE_NBA_BET'
export const UPDATE_NBA_BET = 'nba/games/UPDATE_NBA_BET'
export const OPEN_BET_MODAL = 'nba/games/OPEN_BET_MODAL'
export const CLOSE_BET_MODAL = 'nba/games/CLOSE_BET_MODAL'
