export const FETCH_DASHBOARD_ANNOUNCEMENTS = 'dashboard/FETCH_DASHBOARD_ANNOUNCEMENTS'
export const FETCH_RECENT_PREDICTIONS = 'dashboard/FETCH_RECENT_PREDICTIONS'
export const FETCH_DASHBOARD_POTD = 'dashboard/FETCH_DASHBOARD_POTD'
