export const CHANGE_SELECTED_MODEL = 'nba/gameDetails/CHANGE_SELECTED_MODEL'

export const FETCH_NBA_MATCHES_MODELS = 'nba/gameDetails/FETCH_NBA_MATCHES_MODELS'
export const FETCH_NBA_MATCHES_MODELS_SUCCESS = 'nba/gameDetails/FETCH_NBA_MATCHES_MODELS_SUCCESS'
export const FETCH_NBA_MATCHES_MODELS_FAIL = 'nba/gameDetails/FETCH_NBA_MATCHES_MODELS_FAIL'

export const UPDATE_NBA_MATCHES_MODELS = 'nba/gameDetails/UPDATE_NBA_MATCHES_MODELS'
export const UPDATE_NBA_MATCHES_MODELS_SUCCESS = 'nba/gameDetails/UPDATE_NBA_MATCHES_MODELS_SUCCESS'
export const UPDATE_NBA_MATCHES_MODELS_FAIL = 'nba/gameDetails/UPDATE_NBA_MATCHES_MODELS_FAIL'
