export const FETCH_NBA_MATCHES_MODELS = 'nba/gameDetails/FETCH_NBA_MATCHES_MODELS'

export const UPDATE_NBA_MATCHES_MODELS = 'nba/gameDetails/UPDATE_NBA_MATCHES_MODELS'

export const FETCH_NBA_MATCHES_MODELS_PREDICTION = 'nba/gameDetails/FETCH_NBA_MATCHES_MODELS_PREDICTION'

export const FETCH_NBA_AGGREGATE_TOTALS = 'nba/gameDetails/FETCH_NBA_AGGREGATE_TOTALS'

export const FETCH_NBA_AGGREGATE_SPREADS = 'nba/gameDetails/FETCH_NBA_AGGREGATE_SPREADS'
