export const FETCH_NBA_MATCHES_MODELS = 'nba/gameDetails/FETCH_NBA_MATCHES_MODELS'
export const FETCH_NBA_MATCHES_MODELS_SUCCESS = 'nba/gameDetails/FETCH_NBA_MATCHES_MODELS_SUCCESS'
export const FETCH_NBA_MATCHES_MODELS_FAIL = 'nba/gameDetails/FETCH_NBA_MATCHES_MODELS_FAIL'

export const UPDATE_NBA_MATCHES_MODELS = 'nba/gameDetails/UPDATE_NBA_MATCHES_MODELS'
export const UPDATE_NBA_MATCHES_MODELS_SUCCESS = 'nba/gameDetails/UPDATE_NBA_MATCHES_MODELS_SUCCESS'
export const UPDATE_NBA_MATCHES_MODELS_FAIL = 'nba/gameDetails/UPDATE_NBA_MATCHES_MODELS_FAIL'

export const FETCH_NBA_MATCHES_MODELS_PREDICTION = 'nba/gameDetails/FETCH_NBA_MATCHES_MODELS_PREDICTION'
export const FETCH_NBA_MATCHES_MODELS_PREDICTION_SUCCESS = 'nba/gameDetails/FETCH_NBA_MATCHES_MODELS_PREDICTION_SUCCESS'
export const FETCH_NBA_MATCHES_MODELS_PREDICTION_FAIL = 'nba/gameDetails/FETCH_NBA_MATCHES_MODELS_PREDICTION_FAIL'

export const FETCH_NBA_AGGREGATE_TOTALS = 'nba/gameDetails/FETCH_NBA_AGGREGATE_TOTALS'
export const FETCH_NBA_AGGREGATE_TOTALS_SUCCESS = 'nba/gameDetails/FETCH_NBA_AGGREGATE_TOTALS_SUCCESS'
export const FETCH_NBA_AGGREGATE_TOTALS_FAIL = 'nba/gameDetails/FETCH_NBA_AGGREGATE_TOTALS_FAIL'

export const FETCH_NBA_AGGREGATE_SPREADS = 'nba/gameDetails/FETCH_NBA_AGGREGATE_SPREADS'
export const FETCH_NBA_AGGREGATE_SPREADS_SUCCESS = 'nba/gameDetails/FETCH_NBA_AGGREGATE_SPREADS_SUCCESS'
export const FETCH_NBA_AGGREGATE_SPREADS_FAIL = 'nba/gameDetails/FETCH_NBA_AGGREGATE_SPREADS_FAIL'
