export const FETCH_NBA_PREDICTABILITY = 'nba/gameDetails/FETCH_NBA_PREDICTABILITY'
export const FETCH_NBA_PREDICTABILITY_SUCCESS = 'nba/gameDetails/FETCH_NBA_PREDICTABILITY_SUCCESS'
export const FETCH_NBA_PREDICTABILITY_FAIL = 'nba/gameDetails/FETCH_NBA_PREDICTABILITY_FAIL'
